plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  vue-components@*:
    dependencies:
      eslint-plugin-jsdoc: "*"
      eslint-plugin-json-es: "*"
      eslint-plugin-es: "*"
      eslint-plugin-vue: "*"
      vue-eslint-parser: "*"
  vue-eslint-parser@*:
    dependencies:
      "@typescript-eslint/parser": "*"
  "@typescript-eslint/parser@*":
    dependencies:
      typescript: "*"
